apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestionbancaire-app
  labels:
    app: gestionbancaire-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestionbancaire-app
  strategy:
    type: RollingUpdate			
    rollingUpdate:						
      maxSurge: 1							
      maxUnavailable: 0				
  template:
    metadata:
      labels:
        app: gestionbancaire-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: gestionbancaire-app
          image: 10.0.0.40:5001/gestionbancaire-gestionbancaire:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: gestionbancaire-svc
spec:
  type: NodePort
  ports:
    - port: 1000
      targetPort: 1000
      nodePort: 32464
  selector:
    app: gestionbancaire-app
